// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp3hckBMNx_nPULCdBUqIhwtG5iWAXXaI',
    appId: '1:492041428532:web:06df1543f8c7809a0d3461',
    messagingSenderId: '492041428532',
    projectId: 'final-tasks-app',
    authDomain: 'final-tasks-app.firebaseapp.com',
    storageBucket: 'final-tasks-app.appspot.com',
    measurementId: 'G-N76HK7WTP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB919mpf2lDNamdO49kBDrznE8YFi_Du2w',
    appId: '1:492041428532:android:bc1a8ad9c4a49ccc0d3461',
    messagingSenderId: '492041428532',
    projectId: 'final-tasks-app',
    storageBucket: 'final-tasks-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV5LqE8OKGW7drhiAhcErZATVBHOKAK80',
    appId: '1:492041428532:ios:a0135cd17718001e0d3461',
    messagingSenderId: '492041428532',
    projectId: 'final-tasks-app',
    storageBucket: 'final-tasks-app.appspot.com',
    iosBundleId: 'com.example.finalTasksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV5LqE8OKGW7drhiAhcErZATVBHOKAK80',
    appId: '1:492041428532:ios:d4f6061d9d55e2590d3461',
    messagingSenderId: '492041428532',
    projectId: 'final-tasks-app',
    storageBucket: 'final-tasks-app.appspot.com',
    iosBundleId: 'com.example.finalTasksApp.RunnerTests',
  );
}
